### ISSUE TITLE
Error in the walkthrough example provided in vignette

### ISSUE THREAD

**Issue by pnatsiavas** [yannrivault/packageR_0.1#2]
I am trying to follow the example use of queryMed, as shown in the respective vignette ( https://github.com/yannrivault/queryMed/blob/master/queryMed/vignettes/How-to-queryMed.pdf).

However, when I try to query bio2RDF, an error occurs. Please note that I checked and the Bio2RDF SPARL endpoint is up and running.

```
> query=
+     "SELECT DISTINCT *
+ WHERE {
+ ?db <http://bio2rdf.org/drugbank_vocabulary:x-atc> ?atc .
+ 1
+ ?db dcterms:title ?title .
+ ?db rdfs:label ?label .
+ ?db dcterms:description ?description .
+ ?db <http://bio2rdf.org/drugbank_vocabulary:category> ?category .
+ }
+ limit 5
+ "
> res=sparql(query,url="http://bio2rdf.org/sparql")
Querying http://bio2rdf.org/sparql 
Error in open.connection(con, "rb") : HTTP error 400.
```

I would suggest to confirm that the walkthrough  depicted in the respective vignette works and update the pdf accordingly.

**Comment by yannrivault** [comment]
@pnatsiavas The HTTP error 400 is a response from the server for a bad request.
I think it comes from the "1", line 5. I suppose you copied and pasted code from the pdf file, and thus inserted the page numbering in your R script. Due to this, the server could not understood the request.
The correct query is the following :
```
query="SELECT DISTINCT *
  WHERE  {
    ?db <http://bio2rdf.org/drugbank_vocabulary:x-atc> ?atc .
    ?db dcterms:title ?title .
    ?db rdfs:label ?label .
    ?db dcterms:description ?description .
    ?db <http://bio2rdf.org/drugbank_vocabulary:category> ?category .
  }
limit 5
"
res=sparql(query,url="http://bio2rdf.org/sparql")
res
```

Also, maybe you should try working with the rmd file instead of the pdf.

**Comment by pnatsiavas** [comment]
You are right. Sorry for that... I should have noticed
